### ISSUE TITLE
Help not visible at lower resolutions

### ISSUE THREAD

**Issue by icbat** [Tidwell/scrollstoolbox#1]
At 1366x768 (popular low-mid range laptop resolution), the last bar of the sidebar isn't visible or accessible.

[pic of my browser doing that](http://imgur.com/Hc1AHHc)

**Comment by icbat** [comment]
I'd really like to help with this, but as I'm looking at the CSS, it's bootstrap and fking monstrous. Is there an easier way to modify that web?

**Comment by Tidwell** [comment]
Hey sorry about the late reply on this one.  I think if I just hide the icons on lower resolutions this should resolve the issue.  I'll look at adding the visible-desktop class to the icons on the next update.

**Comment by icbat** [comment]
Hope you're well! Gonna close some of these old ones up :)
